Repository DDING-MIN-YEONG/JNU-LOCKER-BE, pull requests merged in 2025-03, with the labels that each got.

#2 [CHORE] spotless, p6spy, 로깅 설정 적용
  .github/ISSUE_TEMPLATE/작업사항.yml
  build.gradle
  src/main/java/com/jnulocker/JnuLockerApplication.java
  src/main/java/com/jnulocker/infrastructure/persistence/p6spy/P6SpyConfig.java
  src/main/java/com/jnulocker/infrastructure/persistence/p6spy/P6SpyEventListener.java
  src/main/java/com/jnulocker/infrastructure/persistence/p6spy/P6SpyFormatter.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/jnulocker/JnuLockerApplicationTests.java
Labels: enhancement

#5 [FEAT] 예외처리 구현
  src/main/java/com/jnulocker/common/exception/BusinessException.java
  src/main/java/com/jnulocker/common/exception/CommonErrorCode.java
  src/main/java/com/jnulocker/common/exception/ErrorCode.java
  src/main/java/com/jnulocker/common/exception/ErrorResponse.java
  src/main/java/com/jnulocker/common/exception/GlobalExceptionHandler.java
  src/main/java/com/jnulocker/common/exception/ValidationError.java
Labels: enhancement

#7 [FEAT] 공통 응답에 대한 ApiResponse
  src/main/java/com/jnulocker/common/exception/GlobalExceptionHandler.java
  src/main/java/com/jnulocker/common/response/ResponseEntityGenerator.java
Labels: feat 🪄

#10 [DOCS] Swagger 적용
  build.gradle
  src/main/java/com/jnulocker/common/response/ResponseEntityGenerator.java
  src/main/java/com/jnulocker/common/swagger/ApiExceptionExamples.java
  src/main/java/com/jnulocker/common/swagger/ExceptionDoc.java
  src/main/java/com/jnulocker/common/swagger/ExplainError.java
  src/main/java/com/jnulocker/common/swagger/SwaggerExampleHolder.java
  src/main/java/com/jnulocker/common/swagger/SwaggerExceptionDoc.java
  src/main/java/com/jnulocker/common/swagger/exception/ExampleGenerationFailureException.java
  src/main/java/com/jnulocker/common/swagger/exception/SwaggerErrorCode.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: docs 📃

#9 [FEAT] BaseEntity 작성
  src/main/java/com/jnulocker/common/persistence/BaseEntity.java
  src/main/java/com/jnulocker/config/JpaAuditingConfig.java
Labels: feat 🪄

#12 [CHORE] Jib 및 docker compose 구성
  build.gradle
  docker-compose.yml
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: chore 🌲

#16 [CHORE] CI/CD 워크플로우 적용
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/build.yaml
  .github/workflows/cicd.yaml
  .github/workflows/deploy.yaml
  build.gradle
Labels: chore 🌲
