Repository DDING-MIN-YEONG/JNU-LOCKER-BE, pull requests merged in 2025-05, with the labels that each got.

#63 [FEAT] 이벤트 삭제 API 구현
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/DeleteEventExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/EventParticipationRepository.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/FloorRepository.java
  src/main/java/com/jnulocker/events/adapter/out/LockerRepository.java
  src/main/java/com/jnulocker/events/application/port/in/EventCommand.java
  src/main/java/com/jnulocker/events/application/port/out/EventRecordPort.java
  src/main/java/com/jnulocker/events/application/service/EventCommandService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/event/LockerEventDeletedEvent.java
  src/main/java/com/jnulocker/events/event/LockerEventDeletedEventHandler.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/OnlyManagerCanDeleteException.java
  src/main/java/com/jnulocker/events/exception/OpenEventCannotBeDeletedException.java
  src/main/java/com/jnulocker/member/adapter/out/MemberPersistenceAdapter.java
  src/main/java/com/jnulocker/member/adapter/out/MemberRepository.java
  src/main/java/com/jnulocker/member/application/port/in/MemberQuery.java
  src/main/java/com/jnulocker/member/application/port/out/MemberLoadPort.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/CancelMyRegistrationExceptionDocs.java
  src/test/java/com/jnulocker/auth/utils/AuthTestUtil.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/test/java/com/jnulocker/member/utils/MemberTestUtil.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#65 [FEAT] 이메일 인증 시 동일 계정 존재 여부에 대한 검사
  src/main/java/com/jnulocker/auth/adapter/in/docs/MailSendExceptionDocs.java
  src/main/java/com/jnulocker/auth/application/port/in/request/VerifyCodeRequest.java
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/auth/application/service/EmailService.java
  src/main/java/com/jnulocker/events/adapter/in/docs/DeleteEventExceptionDocs.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
Labels: feat 🪄

#67 [FEAT] 이벤트 publish 설정 API 구현
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/in/docs/PublishEventExceptionDocs.java
  src/main/java/com/jnulocker/events/application/port/in/EventCommand.java
  src/main/java/com/jnulocker/events/application/port/in/request/PublishEventRequest.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventListItem.java
  src/main/java/com/jnulocker/events/application/service/EventCommandService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
  src/main/java/com/jnulocker/events/event/LockerEventDeletedEventHandler.java
  src/main/java/com/jnulocker/events/quartz/job/EventPublishJob.java
  src/main/java/com/jnulocker/events/quartz/job/EventUnpublishJob.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
Labels: feat 🪄

#69 [FEAT] 사물함 관리자 가입 승인 API 구현
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/ApproveManagerExceptionDocs.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/application/port/in/ManagerSignupCommand.java
  src/main/java/com/jnulocker/auth/application/port/in/request/ManagerApproveRequest.java
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/auth/exception/AuthErrorCode.java
  src/main/java/com/jnulocker/auth/exception/OnlyGuestCanBeManagerException.java
  src/main/java/com/jnulocker/auth/exception/OnlyManagerCanApproveException.java
  src/main/java/com/jnulocker/auth/exception/OnlySameDepartmentCanApproveException.java
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/auth/security/SecurityUtils.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
  src/main/java/com/jnulocker/member/domain/Member.java
  src/main/java/com/jnulocker/member/exception/MemberErrorCode.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/auth/utils/AuthTestUtil.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/member/utils/MemberTestUtil.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#71 [FEAT] 회원 정보 조회 API 구현
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/member/adapter/in/MemberController.java
  src/main/java/com/jnulocker/member/adapter/in/docs/MemberApi.java
  src/main/java/com/jnulocker/member/application/port/in/MemberQuery.java
  src/main/java/com/jnulocker/member/application/port/in/response/MemberInfoResponse.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/auth/utils/AuthTestUtil.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/member/adapter/in/MemberControllerIntegrationTest.java
  src/test/java/com/jnulocker/organization/utils/OrganizationUtil.java
Labels: feat 🪄

#75 [FEAT] USER의 소속학과에 해당하는 이벤트 목록 조회
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/in/docs/GetMyEventsExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/adapter/out/LockerPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/LockerRepository.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/MyEventResponse.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/port/out/LockerLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/member/adapter/in/docs/GetMemberInfoExceptionDocs.java
  src/main/java/com/jnulocker/member/adapter/in/docs/MemberApi.java
  src/test/java/com/jnulocker/auth/utils/AuthTestUtil.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/test/java/com/jnulocker/member/adapter/in/MemberControllerIntegrationTest.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#77 [FIX] 사물함 신청은 참여한 소속학과의 USER만 가능하도록 수정
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/domain/Locker.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/OnlyParticipationDepartmentCanRegisterException.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationForEventExceptionDocs.java
  src/main/java/com/jnulocker/registration/domain/Registration.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/test/java/com/jnulocker/events/utils/LockerEventContext.java
  src/test/java/com/jnulocker/member/adapter/in/MemberControllerIntegrationTest.java
  src/test/java/com/jnulocker/organization/utils/OrganizationTestUtil.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: fix

#79 [FEAT] MANAGER 가입 대기 목록 조회 API 구현
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/GetPendingManagerExceptionDocs.java
  src/main/java/com/jnulocker/auth/application/port/in/ManagerQuery.java
  src/main/java/com/jnulocker/auth/application/port/in/response/PendingManagerCustomPage.java
  src/main/java/com/jnulocker/auth/application/port/in/response/PendingManagerListItem.java
  src/main/java/com/jnulocker/auth/application/port/in/response/PendingManagerPageable.java
  src/main/java/com/jnulocker/auth/application/service/AuthCommandService.java
  src/main/java/com/jnulocker/auth/application/service/AuthQueryService.java
  src/main/java/com/jnulocker/auth/application/service/EmailService.java
  src/main/java/com/jnulocker/auth/exception/AuthErrorCode.java
  src/main/java/com/jnulocker/auth/exception/FailedToCreateCodeException.java
  src/main/java/com/jnulocker/auth/jwt/TokenProvider.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/member/adapter/out/MemberPersistenceAdapter.java
  src/main/java/com/jnulocker/member/adapter/out/MemberRepository.java
  src/main/java/com/jnulocker/member/application/port/in/MemberQuery.java
  src/main/java/com/jnulocker/member/application/port/out/MemberLoadPort.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/main/resources/application.yml
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
Labels: feat 🪄

#81 [FEAT] 이벤트 ID를 Long에서 UUID로 변경
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/adapter/out/FloorPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/FloorRepository.java
  src/main/java/com/jnulocker/events/application/port/in/EventCommand.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventListItem.java
  src/main/java/com/jnulocker/events/application/port/in/response/MyEventResponse.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/port/out/FloorLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventCommandService.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEvent.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
  src/main/java/com/jnulocker/events/event/LockerEventDeletedEvent.java
  src/main/java/com/jnulocker/events/event/LockerEventDeletedEventHandler.java
  src/main/java/com/jnulocker/events/quartz/job/EventCloseJob.java
  src/main/java/com/jnulocker/events/quartz/job/EventOpenJob.java
  src/main/java/com/jnulocker/events/quartz/job/EventPublishJob.java
  src/main/java/com/jnulocker/events/quartz/job/EventUnpublishJob.java
  src/main/java/com/jnulocker/registration/adapter/in/RegistrationController.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationApi.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationPersistenceAdapter.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationRepository.java
  src/main/java/com/jnulocker/registration/application/port/in/RegistrationCommand.java
  src/main/java/com/jnulocker/registration/application/port/in/RegistrationQuery.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationLoadPort.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationCommandService.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationQueryService.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#83 [FEAT] 이벤트 목록 조회 시 MANAGER 소속 학과 이벤트만 조회되도록 수정
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
Labels: feat 🪄

#85 [CHORE] Prometheus, Grafana 모니터링 구축
  config/grafana.ini
  config/prometheus.yml.tmpl
  deploy.sh
  docker-compose.yml
  nginx/conf.d/default.conf
  src/main/java/com/jnulocker/config/SecurityConfig.java
Labels: chore 🌲

#88 [FIX] 이벤트 생성 시 스케줄링 작업 등록 AFTER_COMMIT 으로 진행
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
Labels: fix

#90 [CHORE] 스케줄링 등록 에러 로깅 및 Grafana 설정 변경
  config/grafana.ini
  docker-compose.yml
  nginx/conf.d/default.conf
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
Labels: chore 🌲

#92 [FIX] Grafana healthcheck 엔드포인트 수정
  docker-compose.yml
Labels: fix

#93 [FEAT] 공지사항 생성 및 조회 API 구현
  src/main/java/com/jnulocker/announce/adapter/in/AnnounceController.java
  src/main/java/com/jnulocker/announce/adapter/in/docs/AnnounceApi.java
  src/main/java/com/jnulocker/announce/adapter/in/docs/CreateAnnounceExceptionDocs.java
  src/main/java/com/jnulocker/announce/adapter/in/docs/GetMyAnnouncesExceptionDocs.java
  src/main/java/com/jnulocker/announce/adapter/out/AnnounceParticipationRepository.java
  src/main/java/com/jnulocker/announce/adapter/out/AnnouncePersistenceAdapter.java
  src/main/java/com/jnulocker/announce/adapter/out/AnnounceRepository.java
  src/main/java/com/jnulocker/announce/application/port/in/AnnounceCommand.java
  src/main/java/com/jnulocker/announce/application/port/in/AnnounceQuery.java
  src/main/java/com/jnulocker/announce/application/port/in/request/CreateAnnounceRequest.java
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnounceCustomPage.java
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnounceListItem.java
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnouncePageable.java
  src/main/java/com/jnulocker/announce/application/port/in/response/MyAnnounceResponse.java
  src/main/java/com/jnulocker/announce/application/port/out/AnnounceLoadPort.java
  src/main/java/com/jnulocker/announce/application/port/out/AnnounceRecordPort.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceCommandService.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceQueryService.java
  src/main/java/com/jnulocker/announce/domain/Announce.java
  src/main/java/com/jnulocker/announce/domain/AnnounceParticipation.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/test/java/com/jnulocker/announce/adapter/in/AnnounceControllerIntegrationTest.java
  src/test/java/com/jnulocker/announce/application/port/in/request/CreateAnnounceRequestTest.java
  src/test/java/com/jnulocker/announce/utils/AnnounceTestUtil.java
  src/testFixtures/java/announce/application/port/in/request/CreateAnnounceRequestTestDataBuilder.java
  src/testFixtures/java/announce/domain/AnnounceTestDataBuilder.java
Labels: feat 🪄

#95 [FEAT] 공지사항 삭제 API 구현
  src/main/java/com/jnulocker/announce/adapter/in/AnnounceController.java
  src/main/java/com/jnulocker/announce/adapter/in/docs/AnnounceApi.java
  src/main/java/com/jnulocker/announce/adapter/in/docs/DeleteAnnounceExceptionDocs.java
  src/main/java/com/jnulocker/announce/adapter/out/AnnounceParticipationRepository.java
  src/main/java/com/jnulocker/announce/adapter/out/AnnouncePersistenceAdapter.java
  src/main/java/com/jnulocker/announce/application/port/in/AnnounceCommand.java
  src/main/java/com/jnulocker/announce/application/port/in/AnnounceQuery.java
  src/main/java/com/jnulocker/announce/application/port/out/AnnounceLoadPort.java
  src/main/java/com/jnulocker/announce/application/port/out/AnnounceRecordPort.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceCommandService.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceQueryService.java
  src/main/java/com/jnulocker/announce/domain/Announce.java
  src/main/java/com/jnulocker/announce/exception/AnnounceErrorCode.java
  src/main/java/com/jnulocker/announce/exception/AnnounceNotFoundException.java
  src/main/java/com/jnulocker/announce/exception/OnlyManagerCanDeleteAnnounceException.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/docs/DeleteEventExceptionDocs.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/OnlyManagerCanDeleteEventException.java
  src/main/java/com/jnulocker/events/exception/OnlyManagerCanDeleteException.java
  src/test/java/com/jnulocker/announce/adapter/in/AnnounceControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
Labels: feat 🪄

#100 [FEAT] 내 정보 조회에 Role 필드 추가
  src/main/java/com/jnulocker/member/application/port/in/response/MemberInfoResponse.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/test/java/com/jnulocker/announce/adapter/in/AnnounceControllerIntegrationTest.java
  src/test/java/com/jnulocker/member/adapter/in/MemberControllerIntegrationTest.java
Labels: feat 🪄

#105 [FEAT] USER 소속학과 대상 이벤트 목록 조회 API 페이지네이션 적용
  build.gradle
  src/main/java/com/jnulocker/common/persistence/querydsl/PathProvider.java
  src/main/java/com/jnulocker/common/persistence/querydsl/QueryDslOrderUtils.java
  src/main/java/com/jnulocker/config/JpaAuditingConfig.java
  src/main/java/com/jnulocker/config/JpaConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepositoryCustom.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepositoryCustomImpl.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventPageable.java
  src/main/java/com/jnulocker/events/application/port/in/response/MyEventCustomPage.java
  src/main/java/com/jnulocker/events/application/port/in/response/MyEventListItem.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/infrastructure/querydsl/EventPathMap.java
  src/test/java/com/jnulocker/common/persistence/querydsl/QueryDslOrderUtilsTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/infrastructure/querydsl/EventPathMapTest.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#107 [FEAT] 이벤트 상세 조회 API 구현
  src/main/java/com/jnulocker/announce/application/service/AnnounceQueryService.java
  src/main/java/com/jnulocker/auth/application/service/AuthQueryService.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/in/docs/GetEventExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventDepartmentResponse.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventResponse.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/OnlyDepartmentMemberCanSeeEventException.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/main/java/com/jnulocker/organization/application/service/OrganizationQueryService.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationQueryService.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
Labels: feat 🪄

#111 [FIX] 공지사항 목록 조회 API 작성자 필드 올바른 값 할당
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnounceListItem.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/ApproveManagerExceptionDocs.java
  src/main/java/com/jnulocker/auth/exception/DepartmentMismatchAuthorizationException.java
  src/main/java/com/jnulocker/member/domain/Member.java
  src/test/java/com/jnulocker/announce/adapter/in/AnnounceControllerIntegrationTest.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
Labels: fix

#115 [FEAT] 로그아웃 API 구현
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnounceDetailResponse.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceQueryService.java
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/application/port/in/LogoutCommand.java
  src/main/java/com/jnulocker/auth/application/service/AuthCommandService.java
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/auth/util/CookieUtil.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
Labels: feat 🪄

#120 [FEAT] JWT 토큰 응답 본문에 담아 전달
  src/main/java/com/jnulocker/announce/application/port/in/response/AnnounceDetailResponse.java
  src/main/java/com/jnulocker/announce/application/service/AnnounceQueryService.java
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/application/port/in/response/AuthTokenResponse.java
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/auth/util/AuthUtil.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventResponse.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
Labels: feat 🪄

#122 [FEAT] 회원탈퇴 API 구현
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/WithdrawExceptionDocs.java
  src/main/java/com/jnulocker/auth/application/port/in/WithdrawCommand.java
  src/main/java/com/jnulocker/auth/application/service/AuthCommandService.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationPersistenceAdapter.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationRepository.java
  src/main/java/com/jnulocker/registration/application/port/in/RegistrationCommand.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationLoadPort.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationRecordPort.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationCommandService.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄

#125 [FEAT] 자신의 소속학과 대상 이벤트 상세 조회 API 구현
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/in/docs/GetEventExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/in/docs/GetMyEventExceptionDocs.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/MyEventResponse.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/EventNotPublishedException.java
  src/main/java/com/jnulocker/events/exception/OnlyDepartmentManagerCanSeeEventException.java
  src/main/java/com/jnulocker/events/exception/OnlyDepartmentMemberCanSeeEventException.java
  src/main/java/com/jnulocker/events/exception/OnlyParticipationDepartmentCanSeeEventException.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationForEventExceptionDocs.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄
