Repository DDING-MIN-YEONG/JNU-LOCKER-BE, pull requests merged in 2025-04, with the labels that each got.

#17 [FEAT] Member, Organization 엔티티
  src/main/java/com/jnulocker/member/domain/Member.java
  src/main/java/com/jnulocker/member/domain/Role.java
  src/main/java/com/jnulocker/organization/domain/Organization.java
  src/main/java/com/jnulocker/organization/domain/Type.java
Labels: feat 🪄

#22 [FEAT] 소속대학 조회 API
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/organization/adapter/in/OrganizationController.java
  src/main/java/com/jnulocker/organization/adapter/out/OrganizationPersistenceAdapter.java
  src/main/java/com/jnulocker/organization/adapter/out/OrganizationRepository.java
  src/main/java/com/jnulocker/organization/application/port/in/OrganizationUseCase.java
  src/main/java/com/jnulocker/organization/application/port/out/OrganizationLoadPort.java
  src/main/java/com/jnulocker/organization/application/service/OrganizationService.java
Labels: feat 🪄

#24 [FEAT] 사물함 조회 API 구현
  src/main/java/com/jnulocker/common/annotation/PersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/in/docs/GetLockerExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/EventRepository.java
  src/main/java/com/jnulocker/events/adapter/out/FloorPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/FloorRepository.java
  src/main/java/com/jnulocker/events/adapter/out/LockerPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/LockerRepository.java
  src/main/java/com/jnulocker/events/application/port/in/GetEventLockerQuery.java
  src/main/java/com/jnulocker/events/application/port/in/response/FloorWithLockersResponse.java
  src/main/java/com/jnulocker/events/application/port/in/response/LockerResponse.java
  src/main/java/com/jnulocker/events/application/port/out/LoadEventPort.java
  src/main/java/com/jnulocker/events/application/port/out/LoadFloorPort.java
  src/main/java/com/jnulocker/events/application/port/out/LoadLockerPort.java
  src/main/java/com/jnulocker/events/application/service/GetEventLockerService.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/EventNotFoundException.java
Labels: feat 🪄

#27 [TEST] 테스트 환경 구성 및 사물함 조회 API 통합 테스트 구현
  build.gradle
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/testFixtures/java/events/builder/EventTestDataBuilder.java
  src/testFixtures/java/organization/builder/OrganizationTestDataBuilder.java
Labels: test 🕶️

#31 [FEAT] Organization, Department로 엔티티 분리
  .gitignore
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/domain/EventParticipation.java
  src/main/java/com/jnulocker/member/domain/Member.java
  src/main/java/com/jnulocker/member/exception/MemberErrorCode.java
  src/main/java/com/jnulocker/member/exception/OnlyGuestCanBeManagerException.java
  src/main/java/com/jnulocker/organization/adapter/in/OrganizationController.java
  src/main/java/com/jnulocker/organization/adapter/in/docs/GetOrganizationsExceptionDocs.java
  src/main/java/com/jnulocker/organization/adapter/in/docs/OrganizationApi.java
  src/main/java/com/jnulocker/organization/adapter/out/DepartmentPersistenceAdapter.java
  src/main/java/com/jnulocker/organization/adapter/out/DepartmentRepository.java
  src/main/java/com/jnulocker/organization/adapter/out/OrganizationPersistenceAdapter.java
  src/main/java/com/jnulocker/organization/adapter/out/OrganizationRepository.java
  src/main/java/com/jnulocker/organization/application/port/in/GetAffiliationQuery.java
  src/main/java/com/jnulocker/organization/application/port/in/GetDepartmentQuery.java
  src/main/java/com/jnulocker/organization/application/port/in/GetOrganizationQuery.java
  src/main/java/com/jnulocker/organization/application/port/in/response/DepartmentResponse.java
  src/main/java/com/jnulocker/organization/application/port/in/response/OrganizationResponse.java
  src/main/java/com/jnulocker/organization/application/port/out/DepartmentLoadPort.java
  src/main/java/com/jnulocker/organization/application/port/out/OrganizationLoadPort.java
  src/main/java/com/jnulocker/organization/application/service/OrganizationQueryService.java
  src/main/java/com/jnulocker/organization/application/service/OrganizationService.java
  src/main/java/com/jnulocker/organization/domain/Department.java
  src/main/java/com/jnulocker/organization/domain/Organization.java
  src/main/java/com/jnulocker/organization/domain/OrganizationType.java
  src/main/java/com/jnulocker/organization/exception/OrganizationErrorCode.java
  src/main/java/com/jnulocker/organization/exception/OrganizationNotFoundException.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/testFixtures/java/events/builder/EventTestDataBuilder.java
  src/testFixtures/java/organization/builder/DepartmentTestDataBuilder.java
  src/testFixtures/java/organization/builder/OrganizationTestDataBuilder.java
Labels: feat 🪄

#33 [FEAT] 이벤트 생성 API 구현
  deploy.sh
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/common/event/DomainEvent.java
  src/main/java/com/jnulocker/common/exception/GlobalExceptionHandler.java
  src/main/java/com/jnulocker/common/response/ResponseEntityGenerator.java
  src/main/java/com/jnulocker/config/WebConfig.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/CreateEventExceptionDocs.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/EventParticipationRepository.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/FloorPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/LockerPersistenceAdapter.java
  src/main/java/com/jnulocker/events/application/port/in/EventCommand.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/request/CreateEventRequest.java
  src/main/java/com/jnulocker/events/application/port/in/request/FloorInfo.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/port/out/EventRecordPort.java
  src/main/java/com/jnulocker/events/application/port/out/FloorLoadPort.java
  src/main/java/com/jnulocker/events/application/port/out/LoadEventPort.java
  src/main/java/com/jnulocker/events/application/port/out/LockerLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventCommandService.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEvent.java
  src/main/java/com/jnulocker/events/event/LockerEventCreatedEventHandler.java
  src/main/java/com/jnulocker/events/quartz/job/EventCloseJob.java
  src/main/java/com/jnulocker/events/quartz/job/EventOpenJob.java
  src/main/java/com/jnulocker/organization/adapter/in/OrganizationController.java
  src/main/java/com/jnulocker/organization/adapter/out/DepartmentPersistenceAdapter.java
  src/main/java/com/jnulocker/organization/adapter/out/DepartmentRepository.java
  src/main/java/com/jnulocker/organization/application/port/in/DepartmentQuery.java
  src/main/java/com/jnulocker/organization/application/port/in/OrganizationQuery.java
  src/main/java/com/jnulocker/organization/application/port/out/DepartmentLoadPort.java
  src/main/java/com/jnulocker/organization/application/service/OrganizationQueryService.java
  src/main/resources/application.yml
  src/testFixtures/java/events/builder/EventTestDataBuilder.java
Labels: feat 🪄

#35 [FEAT] Member에 name 필드 추가
  src/main/java/com/jnulocker/auth/application/port/in/request/UserSignupRequest.java
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/member/domain/Member.java
Labels: feat 🪄

#38 [FEAT] 이벤트 목록 조회 API 구현 및 문서화
  src/main/java/com/jnulocker/common/swagger/model/AbstractPageable.java
  src/main/java/com/jnulocker/events/adapter/in/EventController.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/EventPersistenceAdapter.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/in/request/CreateEventRequest.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventCustomPage.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventListItem.java
  src/main/java/com/jnulocker/events/application/port/in/response/EventPageable.java
  src/main/java/com/jnulocker/events/application/port/in/response/FloorWithLockersResponse.java
  src/main/java/com/jnulocker/events/application/port/in/response/LockerResponse.java
  src/main/java/com/jnulocker/events/application/port/out/EventLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/organization/adapter/in/docs/OrganizationApi.java
  src/main/java/com/jnulocker/organization/application/port/in/response/DepartmentResponse.java
  src/main/java/com/jnulocker/organization/application/port/in/response/OrganizationResponse.java
  src/test/java/com/jnulocker/common/swagger/model/AbstractPageableTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/application/port/in/request/CreateEventRequestTest.java
  src/test/java/com/jnulocker/events/application/port/in/response/EventPageableTest.java
  src/testFixtures/java/common/swagger/model/CustomPageableTestDataBuilder.java
  src/testFixtures/java/events/application/port/in/request/CreateEventRequestTestDataBuilder.java
  src/testFixtures/java/events/application/port/in/request/FloorInfoTestDataBuilder.java
Labels: feat 🪄, test 🕶️, docs 📃

#42 [CHORE] 배포된 FE/BE 서버 CORS 허용
  src/main/java/com/jnulocker/config/WebConfig.java
Labels: chore 🌲

#43 [FEAT] 로그인 API
  build.gradle
  docker-compose.yml
  src/main/java/com/jnulocker/auth/adapter/in/AuthController.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/AuthApi.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/LoginExcepitonDocs.java
  src/main/java/com/jnulocker/auth/adapter/in/docs/ReissueExceptionDocs.java
  src/main/java/com/jnulocker/auth/adapter/out/TokenRepository.java
  src/main/java/com/jnulocker/auth/application/port/in/LoginCommand.java
  src/main/java/com/jnulocker/auth/application/port/in/ReissueCommand.java
  src/main/java/com/jnulocker/auth/application/port/in/request/LoginRequest.java
  src/main/java/com/jnulocker/auth/application/port/in/request/ManagerSignupRequest.java
  src/main/java/com/jnulocker/auth/application/port/in/response/AuthToken.java
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/auth/exception/AuthErrorCode.java
  src/main/java/com/jnulocker/auth/exception/FailAuthenticationException.java
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/auth/jwt/RefreshToken.java
  src/main/java/com/jnulocker/auth/jwt/TokenProvider.java
  src/main/java/com/jnulocker/auth/jwt/TokenType.java
  src/main/java/com/jnulocker/auth/jwt/exception/AuthenticationFailedException.java
  src/main/java/com/jnulocker/auth/jwt/exception/ExpiredTokenException.java
  src/main/java/com/jnulocker/auth/jwt/exception/InvalidAccessTokenException.java
  src/main/java/com/jnulocker/auth/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/jnulocker/auth/jwt/exception/JwtErrorCode.java
  src/main/java/com/jnulocker/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/jnulocker/auth/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/jnulocker/auth/security/CustomUserDetailsService.java
  src/main/java/com/jnulocker/auth/security/SecurityUtils.java
  src/main/java/com/jnulocker/auth/util/CookieUtil.java
  src/main/java/com/jnulocker/config/RedisConfig.java
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/member/adapter/out/MemberPersistenceAdapter.java
  src/main/java/com/jnulocker/member/adapter/out/MemberRepository.java
  src/main/java/com/jnulocker/member/application/port/in/MemberQuery.java
  src/main/java/com/jnulocker/member/application/port/out/MemberLoadPort.java
  src/main/java/com/jnulocker/member/application/service/MemberQueryService.java
  src/main/java/com/jnulocker/member/exception/MemberErrorCode.java
  src/main/java/com/jnulocker/member/exception/MemberNotFoundException.java
  src/main/resources/application.yml
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/auth/adapter/out/TokenRepositoryTest.java
  src/test/java/com/jnulocker/auth/application/port/in/request/LoginRequestTest.java
  src/test/java/com/jnulocker/auth/application/port/in/request/ManagerSignupRequestTest.java
  src/test/java/com/jnulocker/auth/application/port/in/request/UserSignupRequestTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/testFixtures/java/auth/application/port/in/request/LoginRequestTestDataBuilder.java
Labels: feat 🪄, test 🕶️, docs 📃

#49 [FIX] application.yml에 redis 패스워드 추가 및 health-check를 인증 작업에서 제외
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/resources/application.yml
Labels: bug

#51 [FEAT] 사물함 이벤트 생성 로직 층-접두사-범위 계층으로 개선
  src/main/java/com/jnulocker/auth/util/CookieUtil.java
  src/main/java/com/jnulocker/events/application/port/in/request/CreateEventRequest.java
  src/main/java/com/jnulocker/events/application/port/in/request/FloorInfo.java
  src/main/java/com/jnulocker/events/application/port/in/request/LockerRange.java
  src/main/java/com/jnulocker/events/application/port/in/request/PrefixInfo.java
  src/main/java/com/jnulocker/events/application/service/EventCommandService.java
  src/test/java/com/jnulocker/events/application/port/in/request/CreateEventRequestTest.java
  src/testFixtures/java/events/application/port/in/request/CreateEventRequestTestDataBuilder.java
  src/testFixtures/java/events/application/port/in/request/FloorInfoTestDataBuilder.java
Labels: feat 🪄

#53 [FEAT] 사물함 신청 API 구현
  src/main/java/com/jnulocker/config/SecurityConfig.java
  src/main/java/com/jnulocker/events/adapter/in/docs/EventApi.java
  src/main/java/com/jnulocker/events/adapter/out/LockerPersistenceAdapter.java
  src/main/java/com/jnulocker/events/adapter/out/LockerRepository.java
  src/main/java/com/jnulocker/events/application/port/in/EventQuery.java
  src/main/java/com/jnulocker/events/application/port/out/LockerLoadPort.java
  src/main/java/com/jnulocker/events/application/service/EventQueryService.java
  src/main/java/com/jnulocker/events/domain/Event.java
  src/main/java/com/jnulocker/events/domain/Locker.java
  src/main/java/com/jnulocker/events/exception/EventErrorCode.java
  src/main/java/com/jnulocker/events/exception/EventNotOpenException.java
  src/main/java/com/jnulocker/events/exception/InvalidLockerForEventException.java
  src/main/java/com/jnulocker/events/exception/LockerNotFoundException.java
  src/main/java/com/jnulocker/events/exception/LockerUnavailableException.java
  src/main/java/com/jnulocker/registration/adapter/in/RegistrationController.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationApi.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationForEventExceptionDocs.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationPersistenceAdapter.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationRepository.java
  src/main/java/com/jnulocker/registration/application/port/in/RegistrationCommand.java
  src/main/java/com/jnulocker/registration/application/port/in/request/RegisterForEventRequest.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationLoadPort.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationRecordPort.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationCommandService.java
  src/main/java/com/jnulocker/registration/domain/Registration.java
  src/main/java/com/jnulocker/registration/exception/RegistrationAlreadyExistsException.java
  src/main/java/com/jnulocker/registration/exception/RegistrationErrorCode.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/adapter/in/EventControllerIntegrationTest.java
  src/test/java/com/jnulocker/events/utils/EventTestUtil.java
  src/test/java/com/jnulocker/member/utils/MemberTestUtil.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
  src/testFixtures/java/events/domain/EventTestDataBuilder.java
  src/testFixtures/java/member/domain/MemberTestDataBuilder.java
  src/testFixtures/java/organization/domain/DepartmentTestDataBuilder.java
  src/testFixtures/java/organization/domain/OrganizationTestDataBuilder.java
Labels: feat 🪄

#56 [FEAT] 회원가입 시 학번 입력 필드 추가
  src/main/java/com/jnulocker/auth/adapter/in/docs/SignupExceptionDocs.java
  src/main/java/com/jnulocker/auth/application/port/in/request/ManagerSignupRequest.java
  src/main/java/com/jnulocker/auth/application/port/in/request/UserSignupRequest.java
  src/main/java/com/jnulocker/auth/application/service/AuthService.java
  src/main/java/com/jnulocker/auth/exception/AuthErrorCode.java
  src/main/java/com/jnulocker/auth/exception/StudentNumberRequiredException.java
  src/main/java/com/jnulocker/member/domain/Member.java
  src/test/java/com/jnulocker/auth/adapter/in/AuthControllerIntegrationTest.java
  src/test/java/com/jnulocker/auth/application/port/in/request/ManagerSignupRequestTest.java
  src/test/java/com/jnulocker/auth/application/port/in/request/UserSignupRequestTest.java
  src/test/java/com/jnulocker/organization/utils/OrganizationUtil.java
  src/testFixtures/java/auth/application/port/in/request/ManagerSignupRequestTestDataBuilder.java
  src/testFixtures/java/auth/application/port/in/request/UserSignupRequestTestDataBuilder.java
  src/testFixtures/java/member/domain/MemberTestDataBuilder.java
Labels: feat 🪄

#60 [FEAT] 사물함 신청 취소 API 구현
  src/main/java/com/jnulocker/auth/jwt/JwtFilter.java
  src/main/java/com/jnulocker/registration/adapter/in/RegistrationController.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/CancelMyRegistrationExceptionDocs.java
  src/main/java/com/jnulocker/registration/adapter/in/docs/RegistrationApi.java
  src/main/java/com/jnulocker/registration/adapter/out/RegistrationPersistenceAdapter.java
  src/main/java/com/jnulocker/registration/application/port/in/RegistrationCommand.java
  src/main/java/com/jnulocker/registration/application/port/out/RegistrationRecordPort.java
  src/main/java/com/jnulocker/registration/application/service/RegistrationCommandService.java
  src/test/java/com/jnulocker/registration/adapter/in/RegistrationControllerIntegrationTest.java
Labels: feat 🪄, test 🕶️, docs 📃
